name: Scrape event image links

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5.5.0

      - name: Install dependencies
        run: pip3 install -r event_images/requirements.txt

      - name: Run scraper
        run: python3 event_images/scraper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add event_images/data.json
          git diff --staged --quiet || (git commit -m "Update data.json" && git push)
